# Generated by Django 5.1 on 2024-08-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("csq", models.IntegerField(blank=True, null=True)),
                ("sv", models.IntegerField(blank=True, null=True)),
                ("beam", models.IntegerField(blank=True, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("finish", models.DateTimeField(blank=True, null=True)),
                ("bytes", models.BigIntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
