# Generated by Django 5.1 on 2024-08-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_action_alter_event_bytes_alter_event_finish_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="action",
            new_name="transfer",
        ),
    ]
