services:
  web:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/events_db
    volumes:
      - ./app:/app

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events_db

volumes:
  postgres_data:
